### ISSUE TITLE
Autoware fails to recognize small objects on the road

### ISSUE THREAD

**Issue by squizz617** [Autoware-AI/core_perception#54] opened 2021-04-09 12:39 UTC
### Required information:

- Operating system and version: Ubuntu 18.04
- Autoware installation type: Docker image `autoware/autoware:1.14.0-melodic-cuda`, as specified in the Dockerfile of `https://github.com/carla-simulator/carla-autoware` at commit `975b6f3`.
- Autoware version or commit hash - 1.14.0
- ROS distribution and version:
  - ROS Melodic (pre-installed in the docker image)
- ROS installation type:
  - Pre-installed in the docker image

### Description of the bug

* I am running Autoware 1.14.0 (docker image: `autoware/autoware:1.14.0-melodic-cuda`), Carla 0.9.10.1 (docker image: `carlasim/carla:0.9.10.1`) as a simulator and [carla-autoware-bridge](https://github.com/carla-simulator/carla-autoware) at `975b6f3` as a bridge.
* There is an accident that leaves a debris on the path, which is large enough that it should be avoided.
* The vehicle doesn't recognize the debris and hits it: [Camera](https://drive.google.com/file/d/1U7C2Qts8Rbuk6sb94lEbqx7ogSUaOIrl/view?usp=sharing).
* Based on the point clouds, neither the LiDAR nor fusion data seem to have recognized the object: [rviz](https://drive.google.com/file/d/1E8-0jLP8hQNNr2l876yuy9q7D6X7ARzI/view?usp=sharing).
* Please check the [rosbag file](https://drive.google.com/file/d/15Kkej_YokBnjUsjdWQuP7xbss0YiTlEk/view?usp=sharing) for a detailed trace.

### Steps to reproduce the bug

1. Replay the attached rosbag files.

### Expected behavior
Vehicle recognizes the debris and avoids hitting it.

### Actual behavior
Vehicle fails to recognize the debris and hits it.

### Screenshots
Videos attached above.

**Comment by JWhitleyWork** [comment] 2021-04-09 16:34
@squizz617 Unfortunately, this is not something that can be fixed within Autoware. Random debris won't be identified by any camera-based object recognition algorithm because they are trained to only recognize a specific set of classes of objects and if the object is too small to be seen by lidar, then the vehicle can not possibly know to avoid it. This is a problem of sensor coverage, not a bug in Autoware.ai.

**Closed by JWhitleyWork** 2021-04-09 16:34 UTC
Labels: bug
